### ISSUE TITLE
Tombo plot options when the reference is not in the genome

### ISSUE THREAD

**Issue by Nastiya** [nanoporetech/tombo#100]
Dear Marcus & Tombo users.

Where I can find more explanation and examples about Tombo commands, especially the plotting options.

At my first minION experiment, I've tried to sequence a customized plasmid, which I made linear (length ¬ 2000b). In this experiment all the reads had the same sequence. In addition, I've created the reference file (fasta file) since it is not part of the genome.
Now I'm trying to plot the raw signal of the full read (2000b) aligned with the sequence. 
I managed to get such plots for different regions of the reads using "plot max_coverage" option, but I could find a way to create such plots for the entire length.

I'll appreciate your valuable input.

Thank you.
A

**Comment by marcus1487** [comment]
In order to obtain this plot, you can specify the `--num-bases` option to the length of the whole sequence for the `tombo plot genome_locations` command setting the `--genome-locations` option to the center of the sequence. The plotting width is fixed though, so a plot showing 2kb may not be all that informative and very large. Thus a series of plots along the genome may be more helpful. You can specify any number of genome locations to this command, so something like `tombo plot genome_locations --genome-locations chrmN:50 chrmN:150 chrmN:250 [...] --num-bases 100` might be more useful.

You can see all the options to any tombo command by passing the `-h` (`--help`) flag to any tombo command. You can also find details about all plotting commands [here in the Tombo documentation](https://nanoporetech.github.io/tombo/plotting.html).

**Comment by Nastiya** [comment]
Hi Marcus,

I'm still having issues with the plot commands. As previously, I want to plot the full alignment of the  sequence to the squiggle plot. I'm trying to run `tombo plot genome_locations` command and get an error. I have two reference sequences in one fasta file. Their length is  around 400b.

Here is the error that I get:

`(user) user@srv:~$ tombo plot genome_locations --fast5-basedirs ~/12_results/fast5/0/ --genome-locations chrmN:200 --num-bases 400
/home/user/.conda/envs/user/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/user/.conda/envs/user/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
[11:22:30] Parsing genome locations.
[11:22:30] Parsing Tombo index file(s).
******************** WARNING ********************
              Failed to parse tombo index file for /home/user/12_results/fast5/0/ directory. Creating index from FAST5 files.
[11:22:37] Preparing plot data.
******************** ERROR ********************
              No reads in any selected regions.`

Any suggestions of what may be wrong?

**Comment by marcus1487** [comment]
The warning indicates that the Tombo index is not available. To fix this, ensure that the directory here is the exact same one passed to the re-squiggle command.

The error indicates that no reads were mapped to the "chrmN" reference sequence record. This is likely since no reads were assigned to that sequence record. You can view this with the `tombo text_output browser_files` command (the results can be viewed in a genome browser; e.g. IGV). Ensure that this record name is spelled correctly and that reads are in fact mapped to this sequence record name as found in the reference file provided to the resquiggle command.

You can also use the `tombo plot max_coverage` command to see which sequence record has the most reads. The sequence record name (as parsed by Tombo) will appear in the title of the plots produced.

**Comment by Nastiya** [comment]
Thanks, I did use the `tombo plot max_coverage` command, but it didn't do a full alignment of the current curve to the **full** reference sequence. Worth mentioning, that the reference file is a FASTA file that I've created, and it is not part of the genome.

In your comment above for `tombo plot genome_locations` command  you wrote that any number of genome locations can be passed to this command. But here it seems to influence the mapping of the reads to the reference sequence record.

I guess I'm still missing something ;  when I run the  `tombo annotate_raw_with_fastqs` and 'tombo resquiggle' commands, the fast5 files are being modified to contain the sequence from fastq files.
How the  `tombo plot genome_locations` command do the mapping of the current signal/curve and the fastq-sequence file to the given(input) reference sequence?

Thank you.

**Comment by marcus1487** [comment]
The `tombo plot` commands are only displaying the signal to sequence alignments. The alignment procedure is performed in the `tombo resquiggle` step. Full details of this algorithm can be found in the [docs here](https://nanoporetech.github.io/tombo/resquiggle.html).

The passing of multiple sites to the `tombo plot genome_locations` command does not effect the mapping of reads to the reference. This only effects the regions of signal that are plotted. As noted above the signal to sequence assignment is performed in the resquiggle step.

**Comment by Nastiya** [comment]
Hi Marcus,

I'm still having issues with the plotting genome location command.
I did all the processing from the beginning, making sure I choose the correct directories. I also checked in Hdf5 viewer that the resquiggle sequence and the fastq are added to the Fast5 files.

When I run : 
`(user) user@srv:~$ tombo plot genome_locations --fast5-basedirs ~/Data/reads/xx/xx/fast5 --genome-locations chrmN:200 --num-bases 400  `

I get the previous error as above: `No reads in any selected regions`

I also tried the output text commands and got errors:
`(srv): /$ tombo text_output browser_files --fast5-basedirs ~/Data/reads/xx/xx/fast5/0/ --file-types coverage --browser-file-basename my_coverage
/xx/xxx/.conda/envs/xxx/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/xx/xxx/.conda/envs/xxx/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
[15:48:57] Parsing sample Tombo index file(s).
******************** WARNING ********************
	Tombo index file does not exist for one or more directories.
		If --skip-index was not set for re-squiggle command, ensure that the specified directory is the same as for the re-squiggle command.

******************** ERROR ********************
	No reads present in --fast5-basedirs.`

**However**, I do get a plot when I run without any errors:
`(user) user@srv:~$ tombo plot max-coverage --fast5-basedirs ~/Data/reads/xx/xx/fast5  --num-bases 400`
I got a perfect plot but very dense and hard to read because of the 400. But the command does not issue any error regarding the index or the reads.
I can't use lower `--num-bases 400` , since I'm interested to see what happened in the end of the sequence, where the coverage is not ideal.

I don't understand where is the problem; if the problem is in the indexes or in the mapping to the reference, should not this command also raise an error?

Another related question is : Can I plot only the forward sequence ?

Many THANKS!
Anastasia

**Comment by marcus1487** [comment]
The ‘plot max_coverage’ and ‘text_output browser_files’ outputs seem incompatible. The warnings indicating that the tombo index does not exist, show that this directory was not the exact directory called during the resquiggle command. Specifying a subdirectory does not load the index created. But I don’t think this is the core issue here as the sundurectory should still contain all the information in the individual fast5s (just requires more I/O to retrieve). 

I think that this may indicate that an invalid directory was specified to the text output command. 

Back to the original plot genome_locations command, my best guess here would be that the reference record name (chromosome name) is not specified exactly as it is listed in the reference sequence file provided to the resquiggle command. 

For the final question, either forward or reverse strand can be specified for any command taking genomic locations  by adding the strand. For example using ‘chrmN:200:-‘ would specify the reverse strand. When no strand is specified the forward strand is assumed.

**Comment by Nastiya** [comment]
Thank you for your input and all your help.

I checked some reads after the `resquiggle` command in HDF viewer. By 'reference record name (chromosome name) ' you mean that this value should be added based on the name of the reference fasta sequence after the 'resquiggle' command?
 Because in the alignment slot for these reads the 'mapped_chrom =' value was set to 'my_seq'. That is the same name listed in the header of the reference sequence in the reference.fasta file:
>my_seq| descr=my_seq|
ATGCGATGCTGAT.....

Can the issue be that I have two **different** reference sequences in **one** reference.fasta file that I pass to the `resquiggle` command? And still how I manage to run the `max-coverage` command without errors? I would expect it to raise an issue as well.

Thank you!!!

**Comment by marcus1487** [comment]
Yes the header names are used for the sequence location. I have not tested against a fasta with multiple records with the sand mane. But that is likely part of the issue here.

**Comment by Nastiya** [comment]
Hi Marcus.
I run a new sequencing experiment with a new sample, which contained ONLY one sequence, so this time I have only one reference file that looks as follow:
**>ref
AGATAGGATTA...(full reference sequence)**

Then I run the following commands:
1. Albacore for basecalling and to generate .fastq file 
2. Filtered the .fastq file base on length 200-500 
3. porechop to trim the adaptors
So my .fastq don't contain all the reads found in FAST5 directory.

Then I run Tombo commands :
1. `annotate_raw_with_fastq`
2. `resquiggle` commands
3. (user) user@srv:~$ tombo plot genome_locations --fast5-basedirs ~/Data/reads/xx/xx/fast5 --genome-locations chrmN:200 --num-bases 400 `
and got the same error: **`No reads in any selected regions` 4.** 
4. However when I run : 
(user) user@srv:~$ tombo plot max_coverage --fast5-basedirs ~/Data/reads/xx/xx/fast5  --num-bases 400 `  **I do get a plot.**

I would expect that both plots won't work if there is an problem with the reads.  
What does the genome_locations means in such case ? Where does the chrmN appear? how to set correctly chrmN:xxx? How can I check in what regions are my reads? 

By the way, when running: `annotate_raw_with_fastq` and `resquiggle` commands, it runs the command also on the failed FAST5 (by failed I mean : after running albacore basecalling ) files found in the FAST5-base-directory. Is not it affect the results ? How can I filtered them out? 

Thanks.

**Comment by marcus1487** [comment]
Genome locations references a position within the reference files passed to the resquiggle command. From the provided portion of the reference file, the one sequence record name is `ref` and not `chrmN`. Thus replacing this value in the plot command should produce a plot. I am not sure where `chrmN` is coming from in this setting.

In order to see globally where reads are mapping, the `tombo text_output brower_files` command ([docs here](https://nanoporetech.github.io/tombo/text_output.html#tombo-text-output-browser-files)) is recommended. 

The FAST5 base directory can be any directory you choose. So if you would like to only process the `pass` reads, then point the `resquiggle` (and subsequent commands) to the pass folder instead of the reads directory.

**Comment by marcus1487** [comment]
Could you post the full plotting command and error message?

**Comment by Nastiya** [comment]
Hi, attached.

`(user) user@calc:/home.shared/user$ tombo plot genome_locations --fast5-basedirs /home/user /data /reads/fast5/ --genome-locations **ref:200** --num-bases 400
/home/user/.conda/envs/user/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/user/.conda/envs/user/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
[10:01:02] Parsing genome locations.
[10:01:02] Parsing Tombo index file(s).
[10:01:03] Preparing plot data.
******************** ERROR ********************
**No reads in any selected regions.**


(user) user@calc:/home.shared/user$ tombo plot genome_locations --fast5-basedirs /home/user /data/reads/fast5/ --genome-locations **ref:ref** --num-bases 400
/home/user/.conda/envs/user/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/user/.conda/envs/user/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
[10:01:52] Parsing genome locations.
Traceback (most recent call last):
  File "/home/user/.conda/envs/user/bin/tombo", line 11, in <module>
    sys.exit(main())
  File "/home/user/.conda/envs/user/lib/python3.6/site-packages/tombo/__main__.py", line 238, in main
    plot_commands._plot_main(args)
  File "/home/user/.conda/envs/user/lib/python3.6/site-packages/tombo/plot_commands.py", line 2140, in _plot_main
    plot_genome_locations(*base_args, **kwargs)
  File "/home/user/.conda/envs/user/lib/python3.6/site-packages/tombo/plot_commands.py", line 1492, in plot_genome_locations
    0, int(int(pos) - np.floor(num_bases / 2.0) - 1))
**ValueError: invalid literal for int() with base 10: 'ref'**`

**Comment by marcus1487** [comment]
The first command is correctly formatted but as the error indicates there are no reads at the 200 position of the `ref` sequence. Using the `text_output` commands listed previously you can find where your reads are mapped and plot a region with mapped reads. 

The second command is incorrectly formatted. The error message should be more specific here, but the genome locations are to be listed as [reference_name]:[position], where position is an integer index into the specified reference sequence. See `tombo plot genome_locations -h` for more information.

**Comment by trishamoitra30** [comment]
Hi Marcus

I have run the code as follows and at the end of the code pasting the log file with the error (Error faced in the last command tombo plot genome_locations ....);

####
```
#!/bin/bash

# Path Variables
INPUT_FAST5_DIR="/media/btlab/MUKESHSAINI/16SrRNA_nanopore/test/new_fast5"
BASE_CALLED_DIR="/media/btlab/MUKESHSAINI/16SrRNA_nanopore/test/base_called/"
FASTQ_CAT="/media/btlab/MUKESHSAINI/16SrRNA_nanopore/test/fastq_cat"
ALIGN_OUTPUT_DIR="/media/btlab/MUKESHSAINI/16SrRNA_nanopore/test/align_output"
REFERENCE_SEQ="/media/btlab/MUKESHSAINI/16SrRNA_nanopore/test/E.coli_refseq_16SrRNA_fastaseq.fasta"
FAST5_SINGLE_DIR="/media/btlab/MUKESHSAINI/16SrRNA_nanopore/test/f5s"
FINAL_OUTPUT_DIR="/media/btlab/MUKESHSAINI/16SrRNA_nanopore/test/nanopolish_output"

# Create Required Directories
mkdir -p $BASE_CALLED_DIR
mkdir -p $FASTQ_CAT
mkdir -p $ALIGN_OUTPUT_DIR
mkdir -p $FAST5_SINGLE_DIR
mkdir -p $FINAL_OUTPUT_DIR

## TOMBO PROCESSING
# Multi Fast5 to Single Fast5
multi_to_single_fast5 -i $INPUT_FAST5_DIR -s $FAST5_SINGLE_DIR --recursive -t 8

# Tombo Preprocess
tombo preprocess annotate_raw_with_fastqs --fast5-basedir $FAST5_SINGLE_DIR/ --fastq-filenames $FASTQ_CAT/*.fastq --processes 8 --overwrite

# Tombo Resquiggle
tombo resquiggle $FAST5_SINGLE_DIR/ $REFERENCE_SEQ --rna --overwrite --processes 8

# Tombo Filter
tombo filter clear_filters --fast5-basedirs $FAST5_SINGLE_DIR/ --corrected-group RawGenomeCorrected_000 

# Tombo Modification Detection
tombo detect_modifications de_novo --fast5-basedirs $FAST5_SINGLE_DIR/ --statistics-file-basename $FINAL_OUTPUT_DIR/rmtase

# Tombo Plot
tombo plot genome_locations --fast5-basedirs $FAST5_SINGLE_DIR/ --genome-locations "NC_000913.3:1405" --num-bases 21

```
###

Log file 

cat log.txt
nohup: ignoring input
| 5 of 5|###################################################|100% Time: 0:00:27
[00:17:26] Preparing reads and extracting read identifiers.
100%|██████████| 18888/18888 [00:15<00:00, 1232.20it/s]
[00:17:43] Annotating FAST5s with sequence from FASTQs.
100%|██████████| 18888/18888 [02:15<00:00, 138.88it/s]
[00:19:59] Added sequences to a total of 18888 reads.
[00:20:00] Loading minimap2 reference.
[00:20:00] Getting file list.
[00:20:01] Re-squiggling reads (raw signal to genomic sequence alignment).
100%|██████████| 18888/18888 [05:49<00:00, 54.10it/s]
[00:25:51] Final unsuccessful reads summary (19.6% reads unsuccessfully processed; 3699 total reads):
    16.5% (   3124 reads) : Alignment not produced
     3.0% (    563 reads) : Poor raw to expected signal matching (revert with `tombo filter clear_filters`)
     0.1% (     12 reads) : Read event to sequence alignment extends beyond bandwidth
[00:25:51] Saving Tombo reads index to file.
[00:25:51] Parsing Tombo index file(s).
[00:25:51] Clearing all filters.
[00:25:51] Saving Tombo reads index to file.
[00:25:52] All filters successfully cleared!
[00:25:52] Parsing Tombo index file(s).
[00:25:52] Performing de novo model testing against canonical model.
[00:25:52] Calculating read coverage regions.
[00:25:52] Calculating read coverage.
[00:25:52] Performing modified base detection across genomic regions.
100%|██████████| 1/1 [00:32<00:00, 32.70s/it]
**

> [00:26:27] Parsing genome locations.
> [00:26:27] Parsing Tombo index file(s).
> [00:26:27] Preparing plot data.
> ******************** ERROR ********************
>         No reads in any selected regions.

**

**Comment by marcus1487** [comment]
Tombo has been deprecated and no longer supported. I would strongly suggest converting to Remora for signal visualization and manipulation tasks.
