### ISSUE TITLE
Help with 'Motif-specific Alternative Reference Estimation'

### ISSUE THREAD

**Issue by pterzian** [nanoporetech/tombo#179]
Hi Marcus,

I would like to build my own model to detect methylation at a specific motif and I am not sure about the way I should build my command.
Usage says the following arguments are required : 
- `--alternate-model-filename` (ok, name of the future builded model)
- `--alternate-model-name` (Calling a pre-existing model?)
- `--motif-description` (as in GATC or CG)
- `--fast5-basedirs` (ok)

So to be clear I'm not sure about the use of `--alternate-model-name` parameter in this context.

About the `fast5` dataset. Should it be `preprocessed` and `resquiggled` in advance?

Finally about the structure of the file for the `--valid-locations-filename`. I guess it essentially needs the strand and genomic location informations but is there a specific order to the columns and am I missing some needed informations ?

**Comment by marcus1487** [comment]
You can find full documentation for this command and these arguments [here](https://nanoporetech.github.io/tombo/model_training.html#alternative-model-output). To summarize, the `--alternate-model-name` specifies a short name for the model (used to name output files) and the `--valid-locations-filename` is in bed format. For additional documentation on this and other tombo commands the `-h` flag can be added for verbose descriptions of each argument.

**Comment by pterzian** [comment]
So after some tries I can't get over this error:

```
If --skip-index was not set for re-squiggle command, ensure that the specified directory is the same as for the re-squiggle command.
[14:44:05] Calculating read coverage regions.
[14:44:05] Calculating read coverage.
[14:44:16] Extracting average k-mer levels.
100%|██████████| 1164/1164 [29:43<00:00,  1.53s/it]
[15:13:59] Tabulating k-mer model statistics.
******************** ERROR ********************
	At least one modified k-mer is not covered at any poitions by --minimum-test-reads.
		Consider fitting to a smaller k-mer via the --upstream-bases and --downstream-bases, or lowering --minimum-test-reads.
		Note that this may result in a lower quality model.

```

This is the command that I use :
```
tombo build_model estimate_motif_alt_reference \
	--alternate-model-filename GMI.GTWWAC.model \
	--alternate-model-name GMI_mod \
	--motif-description GTWWAC:5 \
	--fast5-basedirs resquiggled_GMI \
	--valid-locations-filename GTWWAC_pos_chrm_strand_730p.tsv \
	--minimum-test-reads 1
```
I did set the `--minimum-test-reads` to 1 so I could avoid the previous error but it still doesn't work. I also reduced my location to the positions I was sure to be covered.

And these are lines from my location file :
```
"lcl|RSp"	2018520	"-"
"lcl|RSp"	2018523	"+"
"lcl|RSp"	2062924	"-"
"lcl|RSp"	2062927	"+"
```

**Comment by marcus1487** [comment]
The first issue here is that the `--valid-locations-filename` should be in [BED format](https://genome.ucsc.edu/FAQ/FAQformat.html#format1). Unfortunately, these incorrectly formatted lines are currently being silently ignored. Thus all locations with the specified `GTWWAC:5` motif are being used for modeling.

I have just pushed a commit (c567725) to display this as a warning (as well as noting the BED file format in the online docs).

The next problem is that the error is indicating that not all k-mers are covered, not that all instances of the motif in the reference are not covered. In other words, each modeled k-mer needs to exist in the reference and be covered by reads (following the restrictions specified, including `--minimum-test-reads`). The default k-mer is a 4-mer (`--upstream-bases` = 1 and `--downstream-bases` = 2). My guess would be that at least one modeled k-mer is not covered by any reads or does not exist in the reference at all. The parameter `--minimum-kmer-observations` is set by default to `1` (which is not likely to produce a very robust model), but this is the parameter that would allow the production from a model given this data.

You could set the `--upstream-bases` and `--downstream-bases` to smaller values, but this again is not likely to produce a robust model.

I look forward to any further questions you might have.

**Comment by pterzian** [comment]
Sorry I took time to answer (just got back from a break). Thanks a lot for those explanations.

I still can't produce any model and I'm still stuck on the same error. I feel kind of stupid because I think I can't get the right bedfile format. Could you validate these lines (or showing me an example) :

```
lcl|RSc	6497	6502	pos1	0	-
lcl|RSc	6500	6505	pos2	0	+
```
In the usage description of `--valid-locations-filename` you say it should contain 6 fields including the strand information. So I just reproduced the 6 first columns described in the UCSC link you provided. `Start` indicates the position of the first letter of the motif and `Stop` the position of the last one. I named each bedlines by enumerating them and gave a score of 0 to all of them.

Could you reopen this topic ? I will definitely have other questions after this one! 

Also to be sure, you wouldn't have some small dataset we could use as a test ?

**Comment by marcus1487** [comment]
The valid locations should be the location of the actual modified bases and not the motif. So the valid locations are likely not the correct "swap base" and are probably filtered out later in processing.

If you would like to train from all possible instances of the motif of interest, then the `--valid-locations-filename` is not necessary. This option is intended for building models from partially modified samples (e.g. CpG methylation in a human sample).

Unfortunately, I do not have a small test set for this option (this option is not even tested in the test commands at the moment).

**Comment by pterzian** [comment]
So following what you say and the documentation you linked on the bedfile format, I should give the position of the "swap base" as `start` and `stop` in the bedfile ?
I will put these `--valid-locations-filename` problems on hold the time I manage to get an actual model produced.

What I would like to understand is this value of `1164` as in this output :
100%|██████████| 1164/1164 [37:07<00:00,  1.91s/it]
Is it the number of modelled k-mer to find in the reads & reference ?
This value does not seem to change while changing `--upstream-bases` or `--downstream-bases` parameters, neither when changing the motif to be trained on.

**Comment by pterzian** [comment]
[update] So I finally manage to produced two custom models, by setting either the  `--upstream-bases` or the `--downstream-bases` to 0.

Then I tried to detect modification calling those new models and I got this error during the detection step :

```
[14:39:34] Parsing Tombo index file(s).
[14:39:44] Performing alternative model testing.
******************** WARNING ********************
	Standard and /work/project/sigenae/PaulT/tombo_train_onresquiggl_GMI/GMI1000.tombo.GTWWAC.model_u1_d0 alternative base models must be estimated using the same k-mer positions.
[14:39:44] Performing specific alternate base(s) testing.
[14:39:44] Calculating read coverage regions.
[14:39:44] Calculating read coverage.
[14:39:56] Performing modified base detection across genomic regions.
  0%|          | 0/1164 [00:00<?, ?it/s]Process Process-1:
Traceback (most recent call last):
  File "/tools/python/3.6.3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/tools/python/3.6.3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/bioinfo/src/Tombo/tombo-v1.5_venv/lib/python3.6/site-packages/tombo/tombo_stats.py", line 4400, in _test_signif_worker
    use_standard_llhr, per_read_q, stat_type, prior_weights)
  File "/usr/local/bioinfo/src/Tombo/tombo-v1.5_venv/lib/python3.6/site-packages/tombo/tombo_stats.py", line 4188, in compute_reg_stats
    r_data, std_ref, alt_refs, use_standard_llhr, reg_data)
  File "/usr/local/bioinfo/src/Tombo/tombo-v1.5_venv/lib/python3.6/site-packages/tombo/tombo_stats.py", line 4048, in compute_alt_model_read_stats
    OCLLHR_HEIGHT, OCLLHR_POWER]))
  File "tombo/_c_helper.pyx", line 338, in tombo._c_helper.c_calc_scaled_llh_ratio_const_var
IndexError: Out of bounds on buffer access (axis 0)

Traceback (most recent call last):
  File "/tools/python/3.6.3/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/tools/python/3.6.3/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/tools/python/3.6.3/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/tools/python/3.6.3/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
[14:39:59] Parsing Tombo index file(s).
[14:40:09] Getting and writing  coverage bedgraphs.
[14:40:09] Calculating read coverage regions.
[14:40:09] Calculating read coverage.
[14:40:25] Loading statistics from file.
[14:40:25] Parsing and outputting statistics wiggles.
```

This is the command that I use :

```
tombo detect_modifications alternative_model  \
   --per-read-statistics-basename GMI_custom_model_perreads \
   --fast5-basedirs resquiggled_GMI/fast5/ \
   --statistics-file-basename GMI.custom_model_2000x \
   --alternate-model-filename GMI1000.tombo.GTWWAC.model_u1_d0

tombo text_output browser_files \
   --fast5-basedirs resquiggled_GMI/fast5/ \
   --genome-fasta GMI1000.genome.fasta \
   --statistics-filename GMI.custom_model_2000x.GTWWAC_mod.tombo.stats \
   --file-type coverage fraction dampened_fraction
```

Sorry for cumulating messages, your help is really appreciated!

**Comment by marcus1487** [comment]
As the warning indicates in order to test using an alternative model, the standard (canonical base model) must be trained using the same k-mer length. This command should result in an error as this model should not be loaded without matched models. This is a bug and I will look into how to short-circuit this run type.

But given that this will result in an early exit from this command (without computing statistics) the remedy is to estimate a canonical base model with the same k-mer length.

**Comment by pterzian** [comment]
So I tried to estimate a canonical base model with this command (with the same parameters than my "best" model) :

```
tombo build_model estimate_reference \
	--tombo-model-filename GMI1000.tombo.canonical.model \
	--fast5-basedirs resquiggled_mAG4/fast5/ \
	--minimum-kmer-observations 10 \
	--upstream-bases 1 \
	--downstream-bases 1
```

and it did exit with this error : 

```
[15:39:44] Parsing Tombo index file(s).
[15:39:54] Calculating read coverage regions.
[15:39:54] Calculating read coverage.
[15:40:13] Extracting average k-mer levels.
100%|██████████| 1164/1164 [1:17:57<00:00,  4.02s/it]
[16:58:12] Tabulating k-mer model statistics.
[16:58:17] Centering model to normalized signal
******************** ERROR ********************
	No reads succcessfully processed for sequence-based normalization parameter re-fitting.
```

I got to say I am a bit lost on this issue as I didn't see in the documentation that I should load both standard and alternative models when calling the `detect_modifications` command. 
Is there a step of validation between a standard and alternative model before doing the detection ? And is it actually possible to train a canonical model on a specified motif only ? If not I guess both models would not share the same k-mers right ?

Looking forward for a solution !

**Comment by marcus1487** [comment]
There is a step performing some validation between the standard and alternative models, but this code is not as thoroughly tested for all use cases, so this may be a case that is falling through the cracks. 

The canonical model must be trained on all k-mers. Thus canonical models will, by definition, cover the specific k-mers provided by the alternative model. Canonical models are used for re-squiggling and a number of plotting and other commands in tombo, so the presence of all k-mers is a requirement. The alternative model is the only one that can be restricted to a specific motif.

As for this error, it appears that there may be a bug that is being silently ignored. [This line in the code](https://github.com/nanoporetech/tombo/blob/e2e847f0c4a0f6a3c2fa4a1a8cd6c7f3a0202adc/tombo/tombo_stats.py#L1682) is skipping all reads at this processing step and thus producing the above error. If you could replace this `continue` with a `raise` and re-install we should be able to track down the root cause of this specific issue.

As for the documentation, the model training documentation page indicates that this is an advanced feature and may require some special care to get right. For the specific reference to passing a standard and alternative model please see the note after the first paragraph on the [model training docs page](https://nanoporetech.github.io/tombo/model_training.html).

Best of luck and I hope we can get you to a fully trained alternative model here.

**Comment by pterzian** [comment]
Here is the raised error after editing the script as you said:

```
[17:11:18] Parsing Tombo index file(s).
[17:11:28] Calculating read coverage regions.
[17:11:28] Calculating read coverage.
[17:11:42] Extracting average k-mer levels.
100%|██████████| 1164/1164 [1:00:36<00:00,  3.12s/it]
[18:12:20] Tabulating k-mer model statistics.
[18:12:29] Centering model to normalized signal
Traceback (most recent call last):
  File "/work/pterzian/Tombo_custom/tombo-v1.5_venv_custom/bin/tombo", line 11, in <module>
    load_entry_point('ont-tombo==1.5', 'console_scripts', 'tombo')()
  File "/work/pterzian/Tombo_custom/tombo-v1.5_venv_custom/lib/python3.6/site-packages/tombo/__main__.py", line 250, in main
    tombo_stats._est_ref_main(args)
  File "/work/pterzian/Tombo_custom/tombo-v1.5_venv_custom/lib/python3.6/site-packages/tombo/tombo_stats.py", line 4773, in _est_ref_main
    args.multiprocess_region_size, args.processes)
  File "/work/pterzian/Tombo_custom/tombo-v1.5_venv_custom/lib/python3.6/site-packages/tombo/tombo_stats.py", line 1734, in estimate_kmer_model
    centered_ref = center_model_to_median_norm(reads_index, init_ref)
  File "/work/pterzian/Tombo_custom/tombo-v1.5_venv_custom/lib/python3.6/site-packages/tombo/tombo_stats.py", line 1676, in center_model_to_median_norm
    r_data)
  File "/work/pterzian/Tombo_custom/tombo-v1.5_venv_custom/lib/python3.6/site-packages/tombo/tombo_stats.py", line 1624, in get_read_corr_factors
    with h5py.File(r_data.fn, 'r+') as fast5_data:
  File "/work/pterzian/Tombo_custom/tombo-v1.5_venv_custom/lib/python3.6/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/work/pterzian/Tombo_custom/tombo-v1.5_venv_custom/lib/python3.6/site-packages/h5py/_hl/files.py", line 172, in make_fid
    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 85, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'resquiggled_mAG4/fast5/121/PCT0078_20181025_0004A30B0028CD73_2_A11_D11_mAG4_read_2811_ch_657_strand.fast5', errno = 13, error message = 'Permission denied', flags = 1, o_flags = 2)
```
I just checked the access permissions of the fast5s and they are all the same (they were processed and resquiggled sometimes ago now and I've been using it since then). 

I'm so on to get this model! As you probably guessed I'd like to see if I can better distinguish one native from one mutant sample using a motif-specific model than using the generalist 6mA one. The thing is I don't have a full PCR-amplified genome to use as a non-modified control, all I have is a mutant for which I know one motif (and only one) not to be modified. So I am kind of afraid this sample won't fit to estimate the canonical model...

**Comment by marcus1487** [comment]
I believe this error indicates that a file does not exist, not that the permissions are not available (I might be wrong here though). This is curious as the files should have been accessed previously in order to extract the k-mer levels (in the main portion of this function). Could you check that this specific file mentioned exists (as the relative path specifies from your current working directory)?

**Comment by pterzian** [comment]
Curious indeed. I already check at the specified path and it exists. I also looked what's inside with hdfview and it seems to contain everything. 
Should I re-install it to try your last modification ?

**Comment by marcus1487** [comment]
It is possible that could fix your issue, but as a quicker test could you try to run this command: `python -c 'import h5py; h5py.File("resquiggled_mAG4/fast5/121/PCT0078_20181025_0004A30B0028CD73_2_A11_D11_mAG4_read_2811_ch_657_strand.fast5", 'r')'; h5py.File("resquiggled_mAG4/fast5/121/PCT0078_20181025_0004A30B0028CD73_2_A11_D11_mAG4_read_2811_ch_657_strand.fast5", 'r+')` and report any errors or successful processing.

**Comment by pterzian** [comment]
I tried it two ways to be sure, but indeed it seems to come from the `"r+"` :

```
python -c 'import h5py; h5py.File("PCT0078_20181025_0004A30B0028CD73_2_A11_D11_mAG4_read_2811_ch_657_strand.fast5", "r"); h5py.File("PCT0078_20181025_0004A30B0028CD73_2_A11_D11_mAG4_read_2811_ch_657_strand.fast5", "r+")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tools/python/3.6.3/lib/python3.6/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/tools/python/3.6.3/lib/python3.6/site-packages/h5py/_hl/files.py", line 172, in make_fid
    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 85, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'PCT0078_20181025_0004A30B0028CD73_2_A11_D11_mAG4_read_2811_ch_657_strand.fast5', errno = 13, error message = 'Permission denied', flags = 1, o_flags = 2)

```
Line by line with another read : 

```
>>> h5py.File("PCT0078_20181025_0004A30B0028CD73_2_A11_D11_mAG4_read_9824_ch_2655_strand.fast5", "r")
<HDF5 file "PCT0078_20181025_0004A30B0028CD73_2_A11_D11_mAG4_read_9824_ch_2655_strand.fast5" (mode r)>
>>> h5py.File("PCT0078_20181025_0004A30B0028CD73_2_A11_D11_mAG4_read_9824_ch_2655_strand.fast5", "r+")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tools/python/3.6.3/lib/python3.6/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/tools/python/3.6.3/lib/python3.6/site-packages/h5py/_hl/files.py", line 172, in make_fid
    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 85, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'PCT0078_20181025_0004A30B0028CD73_2_A11_D11_mAG4_read_9824_ch_2655_strand.fast5', errno = 13, error message = 'Permission denied', flags = 1, o_flags = 2)
```

**Comment by marcus1487** [comment]
In that case the latest fix should solve this issue. Still a bit curious that this is happening as the same read mode was needed for re-squiggle. But in any case I hope this fixes this issue and you are able to produce a model.

**Comment by pterzian** [comment]
So I am not the one who did the resquiggle and the preprocessing on these datasets so maybe this person had permissions I don't actually have. Could it be the reason ? 

I'll keep you posted after I re-installed and tried it. 

Just in case, if I am able to produce the canonical model, should I load both standard and canonical models in the `--alternate-model-filenames` parameter of `tombo detect_modifications` ? I see that the testing is done in the first steps of `detect_modifications` but I don't see any `--standard-model-filenames` in the documentation.

**Comment by marcus1487** [comment]
That would certainly explain this issue. The change I made was an oversight as I usually test on data for which I have read write access. Glad we got to the bottom of that.

For running `tombo detect_modifications`, yes you should provided both standard and alternative model filenames. These arguments are left off of the command line `-h` help in order to make the help more concise for the majority of use cases. As noted in the model estimation docs page note: `This option is generally for advanced users training their own models, so this option is not shown in the command line help documentation, but is available for all applicable commands.`.

**Comment by marcus1487** [comment]
Ah. I think I may see the issue here. Your command should look like this: `tombo detect_modifications --fast5-basedirs fast5s --tombo-model-filename canonical_model.h5 --alternate-model-filenames alternative_model.h5`

**Comment by pterzian** [comment]
Omg I get it now, I've been so blind! Thank you!
