### ISSUE TITLE
Which is more credible when I set --single-read-threshold  ?

### ISSUE THREAD

**Issue by malihhhh** [nanoporetech/tombo#200]
hello!
I am a newbie to tombo, analyzing 5mC in  RNA virus genome sequencing data, see your recommended set --single-read-threshold 0.05-0.1 for RNA data. So I used the following procedures and the same procedures with default --single-read-threshold. And had two figures, but they had 5 different sites, So I don't know which one is better, and how to analyze who is more credible？ 
Thanks!
```
tombo` detect_modifications alternative_model --fast5-basedirs fast5_pass_single --alternate-bases 5mC --single-read-threshold 0.05 0.1 --statistics-file-basename EV71_SR_threshold_0.05_0.1.alt_model --processes 10
tombo plot most_significant --fast5-basedirs fast5_pass_single --statistics-filename EV71_SR_threshold_0.05_0.1.alt_model.5mC.tombo.stats --plot-standard-model --plot-alternate-model 5mC --pdf-filename EV71_SR_threshold_0.05_0.1.most_significant_5mC_sites.pdf
```
--single-read-threshold 0.05-0.1
[EV71_SR_threshold_0.05_0.1.most_significant_5mC_sites.pdf](https://github.com/nanoporetech/tombo/files/3449767/EV71_SR_threshold_0.05_0.1.most_significant_5mC_sites.pdf)
not set --single-read-threshold
[sample.most_significant_5mC_sites.pdf](https://github.com/nanoporetech/tombo/files/3449770/sample.most_significant_5mC_sites.pdf)

**Comment by malihhhh** [comment]
have been thinking about how to judge whether a methylation site is trustworthy, so try to look at the P-value to judge that this method may not be correct. This is what I am trying. And I see the question #182 and find that I have the same purpose as him. I want to use  `plot motif_with_stats` to see  P-value of these potential modification in my genome and to decide which
site is more credible. but I get a wrong message as figure. So I want to ask what went wrong and whether this method works？
`tombo plot motif_with_stats --num-regions 1 --num-statistics 5 --fast5-basedirs fast5_pass_single --motif TCCCTT --genome-fasta EV71.fasta --statistics-filename EV71_SR_threshold_0.05_0.1.alt_model.5mC.tombo.stats --pdf-filename 2941.pdf --plot-standard-model --plot-alternate-model 5mC`
![image](https://user-images.githubusercontent.com/53243176/62184178-753ae500-b38f-11e9-8876-d37655f8fe2e.png)
I have seen some people encounter similar problems, you recommend resquiggle，I tried but did not solve it.

**Comment by marcus1487** [comment]
For the first question concerning the credibility of the alternative thresholds, I'm not sure where the recommendation for the single read threshold of `0.05 0.1` comes from, but this is not the recommendation for the `alternative_model` method. I believe this might be the recommendation for the `de_novo` method on RNA data. Thus I would trust the default settings more in this case. That being said the thresholds for RNA data, in particular, are harder to set as a ground truth modified base data set is much harder to produce.

For the second question, I believe this bug has been fixed in the latest development version. Could try to re-install from github via `pip install git+https://github.com/nanoporetech/tombo/` and rerun the plotting command.

**Comment by malihhhh** [comment]
Thank you for your answer. It really helped me a lot. It turned out that I understood it wrong. I still have a question to ask, can the position of the icon mark deviate from the canonical bases to indicate that it is a possible methylation site?This problem may be silly, but it really puzzled me for a long time.Thanks！
![image](https://user-images.githubusercontent.com/53243176/62264230-b4ca0580-b451-11e9-801e-c9156a616a3d.png)

**Comment by marcus1487** [comment]
Yes. The grey distribution bars (not quite visible at this depth of coverage) show the expected signal levels for canonical bases. Methylation presents as deviations from these expected levels. For the alternative model there is also a red distribution which shows the expected level for the known alternative modified base (e.g. 5mC).
