### ISSUE TITLE
ImportError: No module named c_helper

### ISSUE THREAD

**Issue by JohnUrban** [nanoporetech/tombo#27]
Hi Marcus,

I haven't done much with Tombo since we last spoke (on another github issue here).

Today I updated to the new version. After re-jiggering what the commands looked like in my scripts (since the options changed a bit) - I found I cannot get it to run.

This is the command:
```
tombo resquiggle --overwrite --processes 16 --include-event-stdev ${READS} ${GENOME}
```
(also tried it without ```--overwrite```)

This is the error:
```
Traceback (most recent call last):
  File "/gpfs/data/sgerbi/jurban/software/albacore/tombo/git/tombo/bin/tombo", line 11, in <module>
    load_entry_point('ont-tombo==1.2', 'console_scripts', 'tombo')()
  File "/users/jurban/data/software/albacore/tombo/git/tombo/tombo/__main__.py", line 140, in main
    from . import resquiggle
  File "/users/jurban/data/software/albacore/tombo/git/tombo/tombo/resquiggle.py", line 29, in <module>
    from . import tombo_stats as ts
  File "/users/jurban/data/software/albacore/tombo/git/tombo/tombo/tombo_stats.py", line 33, in <module>
    from . import tombo_helper as th
  File "/users/jurban/data/software/albacore/tombo/git/tombo/tombo/tombo_helper.py", line 29, in <module>
    from .c_helper import c_new_mean_stds, c_new_means, c_apply_outlier_thresh
ImportError: No module named c_helper
```

I can see ```c_helper.pyx``` and ```c_helper.cpp``` in ```tombo/tombo```....

I'm unsure why I was able to run the previous version, but not this one. Do you have any idea what is happening?

Best,

  John

**Comment by marcus1487** [comment]
I think this likely has to do with the python 2/3 inter-compatibility. Are you installing from a local github repo? My guess is that you might have built the code (`pip setup.py`) against one python version but somehow accessed the command line tombo entry point associated with an old install to the other version of python. I think I ran across something similar to this during development.

This may also be way off base. If so, how did you install?

**Comment by JohnUrban** [comment]
That is possible. I will try a few things.

I installed the same way I did last time:
```
git clone https://github.com/nanoporetech/tombo.git

cd tombo 

PYTHONPATH+=:/users/jurban/data/software/albacore/tombo/git/tombo/lib/python2.7/site-packages

mkdir -p /users/jurban/data/software/albacore/tombo/git/tombo//lib/python2.7/site-packages/

python setup.py install --prefix="/users/jurban/data/software/albacore/tombo/git/tombo/"
```

**Comment by JohnUrban** [comment]
As far as I can tell, the same python was used to install and run tombo.

```which python```
In the install and tombo scripts give:
```/gpfs/runtime/opt/python/2.7.3/bin/python```

And that is the same as was written in the tombo/bin/tombo header line.

**Comment by JohnUrban** [comment]
I still have the older version and can confirm everything still works if I use that one instead.

**Comment by marcus1487** [comment]
Not sure if this is related, but when I create a fresh conda instance under python 2.7.3, pip can't find a valid numpy distribution, which is required by cython to compile the *.pyx scripts (like c_helper). I'm thinking something is certainly amiss with the package structure for your install.

Can you update to python 2.7.14? 2.7.3 is pretty out of date (2.7.14 only has 2 years of life left officially) and I think 2.7.14 should be backwards compatible to 2.7.3.

**Comment by marcus1487** [comment]
Ah! I had not actually installed from the setup.py before. I think you have to run `python setup.py build` first and then run your `python setup.py install ...` command. I am not sure how you got the last version to run without a biuld step, but this seemed to fix it for me in this instance. Do let me know if this fixes your installation.

**Comment by JohnUrban** [comment]
Thanks for the suggestion. I just tried it, but it did not change the situation.

**Comment by JohnUrban** [comment]
By the way -- the build step is usually automatically run when running 'python setup.py install'. I can see that it the build step is executed without actually using 'python setup.py build'.

**Comment by JohnUrban** [comment]
Thanks for your help thus far. I will report back after trying a few things.  There is a good chance this will turn out to be something wonky on my side -- so I think it is best for you if you don't rip your hair out looking for something in Tombo. If I can't figure it out tomorrow - I will let you know.

**Comment by JohnUrban** [comment]
Well I tried a different way:
```
module load R/3.3.1
module load conda/sgeager_v1
source activate albacore

conda install -c bioconda ont-tombo
```

But now have a new error:
```
Traceback (most recent call last):
  File "/users/jurban/conda/albacore/bin/tombo", line 6, in <module>
    sys.exit(tombo.__main__.main())
  File "/users/jurban/conda/albacore/lib/python3.6/site-packages/tombo/__main__.py", line 140, in main
    from . import resquiggle
  File "/users/jurban/conda/albacore/lib/python3.6/site-packages/tombo/resquiggle.py", line 37, in <module>
    from .dynamic_programming import traceback, forward_pass
ImportError: cannot import name 'traceback'
```

**Comment by marcus1487** [comment]
These are some very weird errors indeed. Are you able to install tombo in a fresh conda environment?

**Comment by JohnUrban** [comment]
Ok - I did the fresh conda install:
```
module load R/3.3.1
module load conda/sgeager_v1 

conda create -y -n tombo python=3.6
source activate tombo
conda install -c bioconda ont-tombo
```

Now I get this error:
```
Traceback (most recent call last):
  File "/users/jurban/conda/tombo/bin/tombo", line 6, in <module>
    sys.exit(tombo.__main__.main())
  File "/users/jurban/conda/tombo/lib/python3.6/site-packages/tombo/__main__.py", line 140, in main
    from . import resquiggle
  File "/users/jurban/conda/tombo/lib/python3.6/site-packages/tombo/resquiggle.py", line 15, in <module>
    import h5py
  File "/users/jurban/conda/tombo/lib/python3.6/site-packages/h5py/__init__.py", line 26, in <module>
    from . import _errors
ImportError: libhdf5-18d08926.so.10.2.1: cannot open shared object file: No such file or directory
```

**Comment by JohnUrban** [comment]
```ImportError: libhdf5-18d08926.so.10.2.1: cannot open shared object file: No such file or directory```

I can see that the conda tombo directory contains these similarly named files (though none end with 10.2.1):
```
/users/jurban/conda/tombo/lib/libhdf5_cpp.so.12.0.0
/users/jurban/conda/tombo/lib/libhdf5_hl.so.10.1.0
/users/jurban/conda/tombo/lib/libhdf5.so.10.2.0
/users/jurban/conda/tombo/lib/libhdf5_hl.so.10
/users/jurban/conda/tombo/lib/libhdf5.so
/users/jurban/conda/tombo/lib/libhdf5.so.10
/users/jurban/conda/tombo/lib/libhdf5_cpp.so.12
/users/jurban/conda/tombo/lib/libhdf5_hl.so
/users/jurban/conda/tombo/lib/libhdf5_hl_cpp.so.11
/users/jurban/conda/tombo/lib/libhdf5_hl_cpp.so
/users/jurban/conda/tombo/lib/libhdf5_hl_cpp.so.11.1.0
/users/jurban/conda/tombo/lib/libhdf5_cpp.so
```

I can see that ```libhdf5-18d08926.so.10.2.1``` is being called by: ``` /path/to/conda/tombo/lib/python3.6/site-packages/h5py/_errors.cpython-36m-x86_64-linux-gnu.so```

**Comment by JohnUrban** [comment]
And I can see these similarly named files in .conda/pkgs (though again none end with 10.2.1):
```
/users/jurban/.conda/pkgs/hdf5-1.8.17-2/lib/libhdf5.settings
/users/jurban/.conda/pkgs/hdf5-1.8.17-2/lib/libhdf5_cpp.so.12.0.0
/users/jurban/.conda/pkgs/hdf5-1.8.17-2/lib/libhdf5_hl.so.10.1.0
/users/jurban/.conda/pkgs/hdf5-1.8.17-2/lib/libhdf5.so.10.2.0
/users/jurban/.conda/pkgs/hdf5-1.8.17-2/lib/libhdf5_hl.so.10
/users/jurban/.conda/pkgs/hdf5-1.8.17-2/lib/libhdf5.la
/users/jurban/.conda/pkgs/hdf5-1.8.17-2/lib/libhdf5_hl_cpp.la
/users/jurban/.conda/pkgs/hdf5-1.8.17-2/lib/libhdf5.so
/users/jurban/.conda/pkgs/hdf5-1.8.17-2/lib/libhdf5.so.10
/users/jurban/.conda/pkgs/hdf5-1.8.17-2/lib/libhdf5_cpp.la
/users/jurban/.conda/pkgs/hdf5-1.8.17-2/lib/libhdf5_cpp.so.12
/users/jurban/.conda/pkgs/hdf5-1.8.17-2/lib/libhdf5_hl.so
/users/jurban/.conda/pkgs/hdf5-1.8.17-2/lib/libhdf5_hl_cpp.so.11
/users/jurban/.conda/pkgs/hdf5-1.8.17-2/lib/libhdf5_hl_cpp.so
/users/jurban/.conda/pkgs/hdf5-1.8.17-2/lib/libhdf5_hl_cpp.so.11.1.0
/users/jurban/.conda/pkgs/hdf5-1.8.17-2/lib/libhdf5_cpp.so
/users/jurban/.conda/pkgs/hdf5-1.8.17-2/lib/libhdf5_hl.la
```

**Comment by JohnUrban** [comment]
Ok - my apologies. Above I only created a new environment -- but it was not fixing the problem b/c it was linking to the problems in the conda install. I completely uninstalled and re-installed conda:
```
wget https://repo.continuum.io/archive/Anaconda3-5.0.1-Linux-x86_64.sh
export PYTHONPATH=""
bash Anaconda3-5.0.1-Linux-x86_64.sh
#enter
#yes+enter
#~/data/software/conda/anaconda3 + enter
conda create -n tombo python=3.6
source activate tombo
conda install -c bioconda ont-tombo
```

This seems to have solved the problem.
Thanks for your help - and for Tombo obviously.

It looks like the newer version was able to map more of the reads - though the fail rate is still high -- these reads may be more error-prone than minimap2 likes (at least by default).

Old:
```
Correcting 10303 files with 1 subgroup(s)/read(s) each (Will print a dot for each 500 reads completed).
....................
Failed reads summary (9521 total failed):
        Alignment not produced (if all reads failed check for index files) :    6782
        No valid path found through raw signal of long read :   641
        No valid path found through raw signal of short read :  563
        No valid path found through start of raw signal :       1477
        Read event to sequence alignment extends beyond --bandwidth :   5
        Read sequence from SAM and cooresponding cigar string do not agree. :   47
        Too little signal around event-aligned genomic deletion :       6
```

New:
```
Correcting 10303 files with 1 subgroup(s)/read(s) each (Will print a dot for each 1000 reads completed).
.........
Failed reads summary (6828 total failed):
        Alignment not produced :        6782
        Not enough raw signal around potential genomic deletion(s) :    3
        Poor raw to expected signal matching :  25
        Poor raw to expected signal matching at read start :    14
        Read event to sequence alignment extends beyond --bandwidth :   4
```

**Comment by marcus1487** [comment]
I am glad you were able to get Tombo installed!

For the new version failing fewer reads, note that the number of reads failing due to minimap2 is exactly the same (6782). After the alignment step (when Tombo really start to do its work) far fewer reads were filtered out. We can continue the discussion about the mapper in #28, but I'm glad that the new Tombo version worked well on your set of reads!

**Comment by JohnUrban** [comment]
Brutal news....

Although resquiggle worked after that install, now I am getting this error when trying to run plot_genome_location:
```
******************** ERROR ********************
	Must have rpy2, R and R package ggplot2 installed in order to plot. If these packages are installed, run:
		`python -c "import rpy2.robjects; from rpy2.robjects.packages import importr; importr(str('ggplot2'));"`
	 to see installation issues.
```

When I run the suggested command I get:
```
python -c "import rpy2.robjects; from rpy2.robjects.packages import importr; importr(str('ggplot2'));"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/users/jurban/data/software/conda/anaconda3/envs/tombo/lib/python3.6/site-packages/rpy2/robjects/__init__.py", line 16, in <module>
    import rpy2.rinterface as rinterface
  File "/users/jurban/data/software/conda/anaconda3/envs/tombo/lib/python3.6/site-packages/rpy2/rinterface/__init__.py", line 92, in <module>
    from rpy2.rinterface._rinterface import (baseenv,
ImportError: /gpfs/data/sgerbi/jurban/software/conda/anaconda3/envs/tombo/bin/../lib/libreadline.so.6: undefined symbol: PC
```

...which can be recapitulated with just:
```
python -c "import rpy2.robjects; from rpy2.robjects.packages import importr;"
```

**Comment by JohnUrban** [comment]
Info on this error can be found here:
https://github.com/conda-forge/rpy2-feedstock/issues/1

Solutions seems to be:
``` conda install -c conda-forge readline```
or 
```conda install -c conda-forge readline=6.2```

Trying now....

Did not work... new error:
```
python -c "import rpy2.robjects; from rpy2.robjects.packages import importr;"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/users/jurban/data/software/conda/anaconda3/envs/tombo/lib/python3.6/site-packages/rpy2/robjects/__init__.py", line 16, in <module>
    import rpy2.rinterface as rinterface
  File "/users/jurban/data/software/conda/anaconda3/envs/tombo/lib/python3.6/site-packages/rpy2/rinterface/__init__.py", line 92, in <module>
    from rpy2.rinterface._rinterface import (baseenv,
ImportError: libicuuc.so.54: cannot open shared object file: No such file or directory
```

**Comment by marcus1487** [comment]
What does `conda list` give you? In particular do you have some packages (and probably rpy2) installed from conda-forge? Installing some packages from conda-forge and other from default or R causing library linking errors.

**Comment by marcus1487** [comment]
As mentioned in the [gotchas section](https://github.com/nanoporetech/tombo#gotchas) in the readme, conda-forge can cause a lot of issues with rpy2. Try moving conda-forge to the end of the channels list (`conda config --append channels conda-forge`) it and re-installing Tombo.

**Comment by JohnUrban** [comment]
Interesting. I didn't have any packages from conda-forge to start out with for the first error -- but I did use it with the command: ``` conda install -c conda-forge readline=6.2``` to try to solve that error...

**Comment by marcus1487** [comment]
It also might help to have the `r` channel as the highest priority, so all R related packages are coming from the same source. `conda config --prepend channels r`

**Comment by JohnUrban** [comment]
Hey thanks for all your responses. Your last response may have overall solved my problem before I went nuclear. I decided to erase the entire conda install from yesterday and re-install tombo again -- the same way I got it to work yesterday... but now it is not installing:

```
wget https://repo.continuum.io/archive/Anaconda3-5.0.1-Linux-x86_64.sh
bash Anaconda3-5.0.1-Linux-x86_64.sh
#enter
#yes+enter
#~/data/software/conda/anaconda3 + enter
conda create -n tombo python=3.6
source activate tombo
conda install -c bioconda ont-tombo
```

Error:
```
$ conda install -c bioconda ont-tombo
Fetching package metadata .............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - libedit
  - ont-tombo -> r-base 3.4.1* -> ncurses 5.9*
Use "conda info <package>" to see the dependencies for each package.
```

Apparently something changed between today and yesterday...

**Comment by marcus1487** [comment]
Came across this exact issue yesterday: https://github.com/nanoporetech/tombo/issues/26#issuecomment-365995706

Looks like possibly an old version of conda. Give the advice there a shot.

**Comment by marcus1487** [comment]
Okay so it also looks like some of the older issues I have encountered with conda-forge have been fixed (https://github.com/bioconda/bioconda-recipes/pull/7670). Given this advise from the bioconda admins I am switching back to the standard bioconda setup (https://bioconda.github.io/#set-up-channels) with conda-forge as the highest priority channel. Sorry for the confusion over this, but it sounds like bioconda is going through a bit of a flux period right now.

**Comment by mbargull** [comment]
Yeah, sometime last spring/summer that channel priority setup was changed (in https://github.com/bioconda/bioconda-utils/pull/122). Since `bioconda` interacts with many packages from `conda-forge`, this should help with compatibilities between R packages from both channels.

**Comment by JohnUrban** [comment]
This worked - at least to get Tombo installed again (checking the functionality soon):
```
wget https://repo.continuum.io/archive/Anaconda3-5.0.1-Linux-x86_64.sh
bash Anaconda3-5.0.1-Linux-x86_64.sh
#enter
#yes+enter
#~/data/software/conda/anaconda3 + enter
conda update --prefix /users/jurban/data/software/conda/anaconda3 anaconda

conda create -n tombo python=3.6
source activate tombo
conda install -c bioconda ont-tombo
```

**Comment by JohnUrban** [comment]
Still throwing the R related error -- will try some of the other stuff you suggested earlier and report back.
```
python -c "import rpy2.robjects; from rpy2.robjects.packages import importr;"


Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/users/jurban/data/software/conda/anaconda3/envs/tombo/lib/python3.6/site-packages/rpy2/robjects/__init__.py", line 16, in <module>
    import rpy2.rinterface as rinterface
  File "/users/jurban/data/software/conda/anaconda3/envs/tombo/lib/python3.6/site-packages/rpy2/rinterface/__init__.py", line 92, in <module>
    from rpy2.rinterface._rinterface import (baseenv,
ImportError: /gpfs/data/sgerbi/jurban/software/conda/anaconda3/envs/tombo/bin/../lib/libreadline.so.6: undefined symbol: PC
```

**Comment by marcus1487** [comment]
What does your `conda list` look like after a fresh install with the new channel priority?

**Comment by JohnUrban** [comment]
So what should ```.condarc``` look like?

This is what I have:
```
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
```

I then tried doing:
```
conda update --channel-priority --update-dependencies --force --prefix /users/jurban/data/software/conda/anaconda3/envs/tombo ont-tombo
```

Now it is throwing this:
```
/users/jurban/data/software/conda/anaconda3/envs/tombo/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: Warning message:

  warnings.warn(x, RRuntimeWarning)
/users/jurban/data/software/conda/anaconda3/envs/tombo/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: In local({ :
  warnings.warn(x, RRuntimeWarning)
/users/jurban/data/software/conda/anaconda3/envs/tombo/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning:  bytecode version mismatch; using eval

  warnings.warn(x, RRuntimeWarning)
/users/jurban/data/software/conda/anaconda3/envs/tombo/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: During startup - 
  warnings.warn(x, RRuntimeWarning)
/users/jurban/data/software/conda/anaconda3/envs/tombo/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: There were 13 warnings (use warnings() to see them)
  warnings.warn(x, RRuntimeWarning)
/users/jurban/data/software/conda/anaconda3/envs/tombo/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: 

  warnings.warn(x, RRuntimeWarning)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/users/jurban/data/software/conda/anaconda3/envs/tombo/lib/python3.6/site-packages/rpy2/robjects/__init__.py", line 19, in <module>
    from rpy2.robjects.robject import RObjectMixin, RObject
  File "/users/jurban/data/software/conda/anaconda3/envs/tombo/lib/python3.6/site-packages/rpy2/robjects/robject.py", line 58, in <module>
    class RObjectMixin(object):
  File "/users/jurban/data/software/conda/anaconda3/envs/tombo/lib/python3.6/site-packages/rpy2/robjects/robject.py", line 71, in RObjectMixin
    __show = rpy2.rinterface.baseenv.get("show")
LookupError: 'show' not found
```

What do you think the exact set of commands should be from installing conda to installing tombo? Maybe I'm doing some basic stuff wrong. I'm desperate. Apologies for the nuisance!

**Comment by marcus1487** [comment]
1. Set bioconda channel order
```
(conda config --add channels r)
conda config --add channels defaults
conda config --add channels conda-forge
conda config --add channels bioconda
```

2. create conda env:
`conda create -n tombo python=3.6`

3. install tombo:
`conda install ont-tombo`

**Comment by JohnUrban** [comment]
Tried that - got the ```LookupError: 'show' not found``` error above.

Also tried:
```
wget https://repo.continuum.io/archive/Anaconda3-5.0.1-Linux-x86_64.sh
bash Anaconda3-5.0.1-Linux-x86_64.sh
#enter
#yes+enter
#~/data/software/conda/anaconda3 + enter

conda update --all

conda config --add channels r
conda config --add channels defaults
conda config --add channels conda-forge
conda config --add channels bioconda

conda create -n tombo python=3.6
conda activate tombo 
conda install -c bioconda ont-tombo

python -c "import rpy2.robjects; from rpy2.robjects.packages import importr"
```

It gave the same error...

So I tried:
```
python -m rpy2.tests
```

It gave some good info:
```
/users/jurban/data/software/conda/anaconda3/envs/tombo/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: Warning message:

  warnings.warn(x, RRuntimeWarning)
/users/jurban/data/software/conda/anaconda3/envs/tombo/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: In local({ :
  warnings.warn(x, RRuntimeWarning)
/users/jurban/data/software/conda/anaconda3/envs/tombo/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning:  bytecode version mismatch; using eval

  warnings.warn(x, RRuntimeWarning)
/users/jurban/data/software/conda/anaconda3/envs/tombo/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: During startup - 
  warnings.warn(x, RRuntimeWarning)
/users/jurban/data/software/conda/anaconda3/envs/tombo/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: There were 13 warnings (use warnings() to see them)
  warnings.warn(x, RRuntimeWarning)
/users/jurban/data/software/conda/anaconda3/envs/tombo/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: 

  warnings.warn(x, RRuntimeWarning)
rpy2 version: 2.8.5
- built against R version: 3-4.1--72865
- running linked to R version: R version 3.3.1 (2016-06-21)
E
======================================================================
ERROR: __main__ (unittest.loader._FailedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/users/jurban/data/software/conda/anaconda3/envs/tombo/lib/python3.6/site-packages/rpy2/tests.py", line 43, in load_tests
    suite_robjects = loader.discover('robjects', pattern, rpy_root)
  File "/users/jurban/data/software/conda/anaconda3/envs/tombo/lib/python3.6/unittest/loader.py", line 290, in discover
    __import__(start_dir)
  File "/users/jurban/data/software/conda/anaconda3/envs/tombo/lib/python3.6/site-packages/rpy2/robjects/__init__.py", line 19, in <module>
    from rpy2.robjects.robject import RObjectMixin, RObject
  File "/users/jurban/data/software/conda/anaconda3/envs/tombo/lib/python3.6/site-packages/rpy2/robjects/__init__.py", line 19, in <module>
    from rpy2.robjects.robject import RObjectMixin, RObject
  File "/users/jurban/data/software/conda/anaconda3/envs/tombo/lib/python3.6/site-packages/rpy2/robjects/robject.py", line 58, in <module>
    class RObjectMixin(object):
  File "/users/jurban/data/software/conda/anaconda3/envs/tombo/lib/python3.6/site-packages/rpy2/robjects/robject.py", line 71, in RObjectMixin
    __show = rpy2.rinterface.baseenv.get("show")
LookupError: 'show' not found

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
```

In particular:
```
- built against R version: 3-4.1--72865
- running linked to R version: R version 3.3.1 (2016-06-21)
```

So I tried:
```
conda install --update-dependencies --force -c bioconda ont-tombo
```

...didn't change it though.

Looking more into it. Any suggestions still appreciated.

**Comment by JohnUrban** [comment]
Ugh. Solved.

The cluster I'm working on had R in the PATH already -- and it was in front of conda's version....

So I just had to unload that R module (i.e. take it out of the PATH)...

The solution was way simpler than I imagined.
